# Structure of a function

In [1]:
def welcome_message():
  print("hello user")

In [2]:
welcome_message()

hello user

In [3]:
def welcome_message(user="None"):
  print(f"hello {user}")

In [4]:
welcome_message("Phitron")

hello Phitron

In [5]:
def adder(a,b) :

  """
  add two numbers

  a-> int
  b->int


  """
  sum = a+b
  return sum

In [6]:


m = adder(10,30) * 5

print(m)

200

In [7]:
help(adder)

Help on function adder in module __main__:

adder(a, b)
    add two numbers

    a-> int
    b->int

In [8]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

# Different type of argument

In [9]:
def adder(a,b,c) :
  print(f"{a},{b},{c}")


adder(10,30,20)

10,30,20

In [10]:
def adder(*args) :
  for i in args:
    print(i)


adder(10,30,20,40)

10
30
20
40

In [11]:
def adder(a=10,b=30,c=10) :
  print(f"{a},{b},{c}")


adder()

10,30,10

In [12]:
def adder(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}: {value}")

adder(a = 10 , b=30 , c = 40 , n_estimator=50)

a: 10
b: 30
c: 40
n_estimator: 50

# Return type

In [13]:
def welcome_message():
  print("hello user")

print(type(welcome_message()))

hello user
<class 'NoneType'>

In [14]:
def adder(a,b) :
  sum = a+b
  return sum

print(type(adder(10,20)))

<class 'int'>

In [15]:
def adder(a,b) :
  sum = a+b
  return sum

print(type(adder(10.5,20)))

<class 'float'>

In [16]:
def welcome_message(user="None"):
  return f"hello {user}"

print(type(welcome_message()))

<class 'str'>

# iterator

In [17]:
s = {10 , 20 , 30 , 40 , 50 }

s_iter = iter(s)
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))
print(next(s_iter))

for i in s:
    print(i)

50
20
40
10
30
50
20
40
10
30

# generator

In [18]:
lst = [ x for x in range(500) ] # dataset

def data_loader(chunk_size,lst):
    for i in range(0,len(lst),chunk_size):
        yield lst[i:i+chunk_size]


x = data_loader(5,lst)

print(next(x))
print(next(x))

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]

# Lambda, Map and Apply function

In [19]:
import pandas as pd


df = pd.DataFrame({'temperature (F)': [32, 212, 98.6, 68]})
df

df['temperature (C)'] = df['temperature (F)'].apply(lambda x: (x - 32) * 5/9)
df

   temperature (F)  temperature (C)
0             32.0              0.0
1            212.0            100.0
2             98.6             37.0
3             68.0             20.0

In [20]:
def adder(a,b) :
  return [a,b]

print(type(adder(10.5,20)))

#unzip

x,y = adder(10.5,20)

print(y)

<class 'list'>
20

In [21]:
import pandas as pd


df = pd.DataFrame({'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]})

df

df['A'] = df['A'].apply(lambda x: x ** 0.5)


df

          A  B
0  1.000000  5
1  1.414214  6
2  1.732051  7
3  2.000000  8

In [22]:
import pandas as pd

df = pd.DataFrame({'total_spent': [120, 600, 450, 800]})

# Creating a 'High Value' feature on the fly
df['is_high_value'] = df['total_spent'].apply(lambda x: 1 if x > 500 else 0)

df

   total_spent  is_high_value
0          120              0
1          600              1
2          450              0
3          800              1